### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([52, 67, 16, 92, 51, 31, 69, 61, 29, 90, 96, 83, 41, 10,  9],
      dtype=int32)

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[93, 74,  8, 39],
       [18,  7, 52, 61],
       [31, 20, 84, 54],
       [39, 91, 59, 25],
       [65, 95, 80, 23],
       [ 2, 65, 81, 11]], dtype=int32)

In [4]:
# assending
np.sort(a)

array([ 9, 10, 16, 29, 31, 41, 51, 52, 61, 67, 69, 83, 90, 92, 96],
      dtype=int32)

In [5]:
#decending
np.sort(a)[::-1]

array([96, 92, 90, 83, 69, 67, 61, 52, 51, 41, 31, 29, 16, 10,  9],
      dtype=int32)

In [6]:
# row wise sorting
np.sort(b)

array([[ 8, 39, 74, 93],
       [ 7, 18, 52, 61],
       [20, 31, 54, 84],
       [25, 39, 59, 91],
       [23, 65, 80, 95],
       [ 2, 11, 65, 81]], dtype=int32)

In [7]:
# colun wise sorting
np.sort(b, axis=0)

array([[ 2,  7,  8, 11],
       [18, 20, 52, 23],
       [31, 65, 59, 25],
       [39, 74, 80, 39],
       [65, 91, 81, 54],
       [93, 95, 84, 61]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [8]:
a

array([52, 67, 16, 92, 51, 31, 69, 61, 29, 90, 96, 83, 41, 10,  9],
      dtype=int32)

In [9]:
np.append(a,200)

array([ 52,  67,  16,  92,  51,  31,  69,  61,  29,  90,  96,  83,  41,
        10,   9, 200])

In [10]:
b

array([[93, 74,  8, 39],
       [18,  7, 52, 61],
       [31, 20, 84, 54],
       [39, 91, 59, 25],
       [65, 95, 80, 23],
       [ 2, 65, 81, 11]], dtype=int32)

In [12]:
np.append(b, np.ones((b.shape[0],1)), axis=1)

array([[93., 74.,  8., 39.,  1.],
       [18.,  7., 52., 61.,  1.],
       [31., 20., 84., 54.,  1.],
       [39., 91., 59., 25.,  1.],
       [65., 95., 80., 23.,  1.],
       [ 2., 65., 81., 11.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [13]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [14]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [16]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [17]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [18]:
# code
a.shape

(15,)

In [19]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [20]:
np.expand_dims(a,axis=1)

array([[52],
       [67],
       [16],
       [92],
       [51],
       [31],
       [69],
       [61],
       [29],
       [90],
       [96],
       [83],
       [41],
       [10],
       [ 9]], dtype=int32)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [21]:
a

array([52, 67, 16, 92, 51, 31, 69, 61, 29, 90, 96, 83, 41, 10,  9],
      dtype=int32)

In [22]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  3,  4,  6,  7,  9, 10, 11]),)

In [23]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0, 16,  0,  0, 31,  0,  0, 29,  0,  0,  0, 41, 10,  9],
      dtype=int32)

In [24]:
np.where(a%2 == 0,0,a)

array([ 0, 67,  0,  0, 51, 31, 69, 61, 29,  0,  0, 83, 41,  0,  9],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [25]:
a

array([52, 67, 16, 92, 51, 31, 69, 61, 29, 90, 96, 83, 41, 10,  9],
      dtype=int32)

In [26]:
np.argmax(a)

np.int64(10)

b

In [28]:
np.argmax(b,axis=0)

array([0, 4, 2, 1])

In [29]:
np.argmax(b,axis=1)

array([0, 3, 2, 1, 1, 2])

In [30]:
# np.argmin
np.argmin(a)

np.int64(14)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [32]:
 a

array([52, 67, 16, 92, 51, 31, 69, 61, 29, 90, 96, 83, 41, 10,  9],
      dtype=int32)

In [33]:
np.cumsum(a)

array([ 52, 119, 135, 227, 278, 309, 378, 439, 468, 558, 654, 737, 778,
       788, 797])

In [34]:
b

array([[93, 74,  8, 39],
       [18,  7, 52, 61],
       [31, 20, 84, 54],
       [39, 91, 59, 25],
       [65, 95, 80, 23],
       [ 2, 65, 81, 11]], dtype=int32)

In [35]:
np.cumsum(b)

array([  93,  167,  175,  214,  232,  239,  291,  352,  383,  403,  487,
        541,  580,  671,  730,  755,  820,  915,  995, 1018, 1020, 1085,
       1166, 1177])

In [36]:
np.cumsum(b, axis=0)

array([[ 93,  74,   8,  39],
       [111,  81,  60, 100],
       [142, 101, 144, 154],
       [181, 192, 203, 179],
       [246, 287, 283, 202],
       [248, 352, 364, 213]])

In [37]:
np.cumsum(b, axis=1)

array([[ 93, 167, 175, 214],
       [ 18,  25,  77, 138],
       [ 31,  51, 135, 189],
       [ 39, 130, 189, 214],
       [ 65, 160, 240, 263],
       [  2,  67, 148, 159]])

In [38]:
# np.cumprod

np.cumprod(a)

array([                  52,                 3484,                55744,
                    5128448,            261550848,           8108076288,
               559457263872,       34126893096192,      989679899789568,
          89071190981061120,  8550834334181867520,  8742974936132042752,
        7973834980932272128,  5951373514484514816, -1777870590768021504])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [39]:
a

array([52, 67, 16, 92, 51, 31, 69, 61, 29, 90, 96, 83, 41, 10,  9],
      dtype=int32)

In [40]:
np.percentile(a,100)

np.float64(96.0)

In [41]:
np.percentile(a,0)

np.float64(9.0)

In [42]:
np.percentile(a,50)

np.float64(52.0)

In [43]:
np.median(a)

np.float64(52.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [44]:
a

array([52, 67, 16, 92, 51, 31, 69, 61, 29, 90, 96, 83, 41, 10,  9],
      dtype=int32)

In [46]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 1, 1, 1, 2, 3, 0, 1, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [45]:
np.histogram(a,bins=[0,50,100])

(array([6, 9]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [47]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [48]:
a

array([52, 67, 16, 92, 51, 31, 69, 61, 29, 90, 96, 83, 41, 10,  9],
      dtype=int32)

In [49]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([90, 10], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [50]:
a

array([52, 67, 16, 92, 51, 31, 69, 61, 29, 90, 96, 83, 41, 10,  9],
      dtype=int32)

In [51]:
np.flip(a)

array([ 9, 10, 41, 83, 96, 90, 29, 61, 69, 31, 51, 92, 16, 67, 52],
      dtype=int32)

In [52]:
b

array([[93, 74,  8, 39],
       [18,  7, 52, 61],
       [31, 20, 84, 54],
       [39, 91, 59, 25],
       [65, 95, 80, 23],
       [ 2, 65, 81, 11]], dtype=int32)

In [53]:
np.flip(b)

array([[11, 81, 65,  2],
       [23, 80, 95, 65],
       [25, 59, 91, 39],
       [54, 84, 20, 31],
       [61, 52,  7, 18],
       [39,  8, 74, 93]], dtype=int32)

In [54]:
np.flip(b, axis=0)

array([[ 2, 65, 81, 11],
       [65, 95, 80, 23],
       [39, 91, 59, 25],
       [31, 20, 84, 54],
       [18,  7, 52, 61],
       [93, 74,  8, 39]], dtype=int32)

In [55]:
np.flip(b, axis=1)

array([[39,  8, 74, 93],
       [61, 52,  7, 18],
       [54, 84, 20, 31],
       [25, 59, 91, 39],
       [23, 80, 95, 65],
       [11, 81, 65,  2]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [56]:
a

array([52, 67, 16, 92, 51, 31, 69, 61, 29, 90, 96, 83, 41, 10,  9],
      dtype=int32)

In [57]:
np.put(a,[0,1],[110,530])

In [58]:
a

array([110, 530,  16,  92,  51,  31,  69,  61,  29,  90,  96,  83,  41,
        10,   9], dtype=int32)

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [59]:
a

array([110, 530,  16,  92,  51,  31,  69,  61,  29,  90,  96,  83,  41,
        10,   9], dtype=int32)

In [60]:
np.delete(a,[0,2,4])

array([530,  92,  31,  69,  61,  29,  90,  96,  83,  41,  10,   9],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [61]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [62]:
np.intersect1d(m,n)

array([3, 4, 5])

In [63]:
np.setdiff1d(n,m)

array([6, 7])

In [64]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [65]:
m[np.in1d(m,1)]

C:\Users\KNIGHT RAJ\AppData\Local\Temp\ipykernel_16440\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [66]:
a

array([110, 530,  16,  92,  51,  31,  69,  61,  29,  90,  96,  83,  41,
        10,   9], dtype=int32)

In [67]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 75, 51, 31, 69, 61, 29, 75, 75, 75, 41, 25, 25],
      dtype=int32)

In [68]:
# 17. np.swapaxes

In [70]:
# 18. np.uniform

In [71]:
# 19. np.count_nonzero

In [72]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [73]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [74]:
# 25. np.allclose and equals