### What is numpy?

- NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

- At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## Creating Numpy Arrays

In [4]:
# np.array
import numpy as np 

a = np.array([1,2,3,4])
print(a)  #also called vector
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
# 2D 
b = np.array([[1,2,3], [4,5,6]])
print(b) # called Matrix
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [8]:
# 3D
c = np.array([[[1,2],[3,4]],[[4,6],[7,8]]])
print(c) # called Tesor

[[[1 2]
  [3 4]]

 [[4 6]
  [7 8]]]


In [9]:
# dtype
np.array([1,2,3], dtype = float)

array([1., 2., 3.])

In [11]:
# dtype
np.array([1,2,3], dtype = bool)

array([ True,  True,  True])

In [12]:
# dtype
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
# np.arange 
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
#np.ones and np.zero

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.random.random((3,4))

array([[0.27555616, 0.95120854, 0.47376844, 0.40148504],
       [0.05935155, 0.95696709, 0.82462471, 0.39153829],
       [0.04752547, 0.18366104, 0.5617656 , 0.10323118]])

In [23]:
# np.linspace
np.linspace(-10,10,10)  # equal distace create point

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [26]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [29]:
a1 = np.arange(10)
a2 = np.arange(12,dtype= float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [30]:
# ndim 
a1.ndim

1

In [31]:
a2.ndim

2

In [32]:
a3.ndim

3

In [33]:
# shape

a1.shape

(10,)

In [35]:
a2.shape
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [38]:
a3.shape

(2, 2, 2)

In [39]:
# size 
a3.size

8

In [41]:
a2.size

12

In [42]:
# itemsize 
a3.itemsize

8

In [44]:
a2.itemsize

8

In [46]:
# dtype 
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


## Changing Datatype

In [48]:
 # astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array Operations

In [49]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [51]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
# Scalar Operations 

# arthmetic  like +, -, *, %, /
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [53]:
# relational LIKE <, >, ==, <=, >=
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [54]:
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [56]:
# vector Operations

# arthmetic +, -, *, **, %, /
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

## Array Functions

In [57]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[87.,  0., 70.],
       [72., 97., 43.],
       [64., 29., 18.]])

In [59]:
# max/ min/ sum/ prod 

np.sum(a1)

np.float64(480.0)

In [60]:
np.prod(a1)

np.float64(0.0)

In [61]:
# 0 -> column , 1-> row

np.max(a1, axis=1)

array([87., 97., 64.])

In [62]:
# mean/median/mode 

np.mean(a1)

np.float64(53.333333333333336)

In [63]:
np.median(a1)

np.float64(64.0)

In [64]:
# trigonometric Function

np.sin(a1)

array([[-0.82181784,  0.        ,  0.77389068],
       [ 0.25382336,  0.37960774, -0.83177474],
       [ 0.92002604, -0.66363388, -0.75098725]])

In [68]:
# dot product 

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12).reshape(4,3)

np.dot(a2,a3)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [70]:
# log and exponents

np.log(a1)

C:\Users\KNIGHT RAJ\AppData\Local\Temp\ipykernel_8424\174362789.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[4.46590812,       -inf, 4.24849524],
       [4.27666612, 4.57471098, 3.76120012],
       [4.15888308, 3.36729583, 2.89037176]])

In [72]:
np.exp(a1)

array([[6.07603023e+37, 1.00000000e+00, 2.51543867e+30],
       [1.85867175e+31, 1.33833472e+42, 4.72783947e+18],
       [6.23514908e+27, 3.93133430e+12, 6.56599691e+07]])

In [73]:
# round/ floor/ ceil 

np.round(np.random.random((2,3))*100)

array([[52., 85., 39.],
       [82., 76., 13.]])

## Indexing and Slicing

In [76]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [78]:
# indexing

a1[0]

np.int64(0)

In [79]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
a2[1,2] # find 6

np.int64(6)

In [81]:
a2[2,3]

np.int64(11)

In [82]:
a2[1,0]

np.int64(4)

In [83]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [84]:
a3[1,0,1] #find 5

np.int64(5)

In [85]:
a3[0,1,1] # find 3

np.int64(3)

In [86]:
# slicing 

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a1[2:5]

array([2, 3, 4])

In [88]:
a1[2:7:2]

array([2, 4, 6])

In [89]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
a2[0,:]

array([0, 1, 2, 3])

In [91]:
a2[:,2]

array([ 2,  6, 10])

In [92]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [93]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [101]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [102]:
a2[1,::3]

array([4, 7])

In [118]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [121]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [123]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [124]:
a3[0,1,:]

array([3, 4, 5])

In [125]:
a3[1,:,1]

array([10, 13, 16])

In [126]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [128]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Iterating

In [129]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [135]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [136]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [137]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [139]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [140]:
# transpose

np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [141]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [143]:
# reval 
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [145]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [151]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)


np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [152]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [153]:
# horizontal split 
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [155]:
# vertical split 
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [156]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]